### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by LittleRey** [xiaokaixuan/ss-v2ray-plugin#1]
端口填什么，kubesail搭建了也是无法使用，

**Comment by alance123** [comment]
> 端口填什么，kubesail搭建了也是无法使用，

我试了一下，端口443可以用

**Comment by StephenAnboer** [comment]
> > 端口填什么，kubesail搭建了也是无法使用，
> 
> 我试了一下，端口443可以用

地址写expose的域名，端口443，plugin那里怎么写呀？host也是这个域名？路径/ws ，允许tls，允许不安全的？

**Comment by rlee024426** [comment]
> > > 端口填什么，kubesail搭建了也是无法使用，
> > 
> > 
> > 我试了一下，端口443可以用
> 
> 地址写expose的域名，端口443，plugin那里怎么写呀？host也是这个域名？路径/ws ，允许tls，允许不安全的？

plugin是v2ray-plugin

**Comment by rlee024426** [comment]
> > > 端口填什么，kubesail搭建了也是无法使用，
> > 
> > 
> > 我试了一下，端口443可以用
> 
> 地址写expose的域名，端口443，plugin那里怎么写呀？host也是这个域名？路径/ws ，允许tls，允许不安全的？

kubesail基本是秒挂，用不了多久

**Comment by playnetcn** [comment]
kubesail不允许部署和使用这类程序，部署上也用不了，秒挂

**Comment by xiaokaixuan** [comment]
KubeSai用不成了。可以部署到Heroku，使用CloudFlare workers加速，应急用还是可以的。
