### ISSUE TITLE
KubeSail部署程序只能免费用7天问题

### ISSUE THREAD

**Issue by playnetcn** [xiaokaixuan/ss-v2ray-plugin#2]
KubeSail部署程序之后只能免费使用7天，官网会发邮件通知是否免费继续使用还是付费，点击继续免费之后，程序配置在，但是停止工作。只能重新部署，不知道是否有方法解决？

**Comment by alance123** [comment]
> KubeSail部署程序之后只能免费使用7天，7天之后程序就会停止工作。只能重新部署，不知道是否有方法解决？

没有搞清楚kubesail怎么部署，怎么使用？有没有详细教程？谢谢。
